# Generated by Django 3.2 on 2022-05-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='GB')),
                ('email', models.EmailField(max_length=254)),
                ('treatment', models.IntegerField(choices=[(0, 'Facial'), (1, 'Make-Up'), (2, 'Pedicure'), (3, 'Manicure'), (4, 'EyeBrow Plucking')])),
                ('booking_time', models.DateField(auto_now=True)),
                ('appointment_date', models.DateField()),
                ('appointment_slot', models.IntegerField(choices=[(0, '9am-11am'), (1, '12pm-2pm'), (2, '3pm-5pm'), (3, '6pm-8pm')])),
                ('address_line_one', models.CharField(max_length=60)),
                ('address_line_two', models.CharField(max_length=60)),
                ('address_line_three', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=10)),
                ('addition_info', models.TextField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
