# Generated by Django 3.2 on 2022-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address_line_three',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
