# Generated by Django 3.2 on 2022-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['appointment_date', 'appointment_slot']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='addition_info',
            new_name='additional_info',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('appointment_date', 'appointment_slot'), name='unique_booking'),
        ),
    ]
