# Generated by Django 3.2 on 2022-05-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_address_line_three'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='addition_info',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address_line_three',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
