# Generated by Django 3.2 on 2022-05-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220527_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='treatment',
            field=models.IntegerField(choices=[(0, 'Facial'), (1, 'Make-Up'), (2, 'Pedicure'), (3, 'Manicure'), (4, 'Hair Styling')]),
        ),
    ]
