# Generated by Django 3.2 on 2022-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancelled',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'CANCELLED')], default=0),
        ),
    ]
