# Generated by Django 3.2 on 2022-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
