# Generated by Django 3.2 on 2022-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_type', models.IntegerField(choices=[(0, 'Facial'), (1, 'Make-Up'), (2, 'Pedicure'), (3, 'Manicure'), (4, 'Hair Styling')])),
                ('treatment_name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('treatment_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('treatment_description', models.TextField()),
                ('treatment_time', models.CharField(max_length=50)),
            ],
        ),
    ]
