# Generated by Django 3.2 on 2022-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.IntegerField(choices=[(0, 'Facial'), (1, 'Make-Up'), (2, 'Pedicure'), (3, 'Manicure'), (4, 'Hair Styling')])),
                ('treatment_name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(verbose_name=models.CharField(max_length=60, unique=True))),
                ('treatment_price', models.FloatField()),
                ('treatment_description', models.TextField()),
            ],
        ),
    ]
