# Generated by Django 3.2 on 2022-06-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_alter_treatment_treatment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_time',
            field=models.CharField(default='1hr', max_length=50),
            preserve_default=False,
        ),
    ]
