# Generated by Django 3.2 on 2022-05-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='GB')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address_line_one', models.CharField(max_length=60)),
                ('address_line_two', models.CharField(max_length=60)),
                ('address_line_three', models.CharField(max_length=60, null=True)),
                ('city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=10)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking.Profile.bookings+', to='booking.booking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
